openapi: 3.0.3
info:
  title: Brewanator API
  description: API for the Brewanator backend service
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  
  /api/packages:
    get:
      operationId: listPackages
      summary: List installed packages
      description: Returns a list of all packages installed via Homebrew
      responses:
        '200':
          description: List of installed packages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewListResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /api/packages/{packageName}:
    get:
      operationId: getPackageInfo
      summary: Get package information
      description: Returns detailed information about a specific package including dependencies and dependents
      parameters:
        - name: packageName
          in: path
          required: true
          description: Name of the package to get information for
          schema:
            type: string
            example: "node"
      responses:
        '200':
          description: Package information with dependencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewPackageInfo'
        '400':
          description: Bad request - package name is required
          content:
            text/plain:
              schema:
                type: string
                example: "Package name is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewPackageInfo'

  /api/packages/search/{query}:
    get:
      operationId: searchPackages
      summary: Search for packages
      description: Searches for packages using the brew search command
      parameters:
        - name: query
          in: path
          required: true
          description: Search query to find packages
          schema:
            type: string
            example: "python"
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '400':
          description: Bad request - search query is required
          content:
            text/plain:
              schema:
                type: string
                example: "Search query is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

  /api/packages/last-update:
    get:
      operationId: getLastUpdateTime
      summary: Get last update time
      description: Returns the timestamp of when Homebrew was last updated
      responses:
        '200':
          description: Last update time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

  /api/packages/upgrade:
    post:
      operationId: updateAndUpgrade
      summary: Update and upgrade Homebrew
      description: Updates Homebrew itself and then upgrades all installed packages
      responses:
        '200':
          description: Update and upgrade completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

  /api/packages/doctor:
    post:
      operationId: runDoctor
      summary: Run brew doctor
      description: Runs brew doctor to diagnose and fix common Homebrew issues
      responses:
        '200':
          description: Brew doctor completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

  /api/packages/{packageName}/install:
    post:
      operationId: installPackage
      summary: Install a package
      description: Installs a package using the brew install command
      parameters:
        - name: packageName
          in: path
          required: true
          description: Name of the package to install
          schema:
            type: string
            example: "node"
      responses:
        '200':
          description: Package installation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '400':
          description: Bad request - package name is required
          content:
            text/plain:
              schema:
                type: string
                example: "Package name is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

  /api/packages/{packageName}/uninstall:
    delete:
      operationId: uninstallPackage
      summary: Uninstall a package
      description: Uninstalls a package using the brew uninstall command
      parameters:
        - name: packageName
          in: path
          required: true
          description: Name of the package to uninstall
          schema:
            type: string
            example: "node"
      responses:
        '200':
          description: Package uninstallation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'
        '400':
          description: Bad request - package name is required
          content:
            text/plain:
              schema:
                type: string
                example: "Package name is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrewCommandResult'

components:
  schemas:
    BrewListResult:
      type: object
      properties:
        packages:
          type: array
          items:
            $ref: '#/components/schemas/BrewPackage'
          description: List of installed packages
        isSuccess:
          type: boolean
          description: Whether the command executed successfully
        errorMessage:
          type: string
          nullable: true
          description: Error message if the command failed
        totalCount:
          type: integer
          description: Total number of packages
      required:
        - packages
        - isSuccess
        - totalCount
    
    BrewPackage:
      type: object
      properties:
        name:
          type: string
          description: Package name
        version:
          type: string
          nullable: true
          description: Package version (if available)
      required:
        - name

    BrewCommandResult:
      type: object
      properties:
        isSuccess:
          type: boolean
          description: Whether the command executed successfully
        output:
          type: string
          description: The command output
        errorMessage:
          type: string
          nullable: true
          description: Error message if the command failed
        exitCode:
          type: integer
          description: Exit code of the command
      required:
        - isSuccess
        - output

    BrewPackageInfo:
      type: object
      properties:
        name:
          type: string
          description: Package name
        description:
          type: string
          nullable: true
          description: Package description
        version:
          type: string
          nullable: true
          description: Package version
        dependencies:
          type: array
          items:
            type: string
          description: List of packages this package depends on
        dependents:
          type: array
          items:
            type: string
          description: List of packages that depend on this package
        output:
          type: string
          description: The command output from brew info
        isSuccess:
          type: boolean
          description: Whether the command executed successfully
        errorMessage:
          type: string
          nullable: true
          description: Error message if the command failed
      required:
        - name
        - output
        - isSuccess
        - dependencies
        - dependents
